# Generated by Django 3.0.8 on 2020-07-31 16:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoApp', '0003_auto_20200731_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
